# Generated by Django 4.1.5 on 2023-06-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintage', '0002_post_nb_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
