# Generated by Django 4.1.5 on 2023-06-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintage', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
