# Generated by Django 4.1.5 on 2023-06-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintage', '0005_profile_nb_followers_alter_post_price_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nb_following',
            field=models.IntegerField(default=0),
        ),
    ]
