# Generated by Django 4.1.5 on 2023-06-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintage', '0007_post_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
