# Generated by Django 4.1.5 on 2023-06-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintage', '0009_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='comment',
            field=models.TextField(default='nothing to say', max_length=1000),
        ),
    ]
