# Generated by Django 4.1.5 on 2023-06-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vintage', '0011_transaction_comment_transaction_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='image',
            new_name='screenshot',
        ),
    ]
